### ISSUE TITLE
blz file generation

### ISSUE THREAD

**Issue by quickquestion** [infiniteam/avacodo#7]
I wrote a script to generate simplified blz and i have different results than the file attached to the project:

M 10050005;C6;**100**;false;BELADEB1DB5;0  --  10050005;C6;000;false;BELADEB1DB5;0
M 10050006;D1;**100**;false;BELADEB1DB6;0  --  10050006;D1;000;false;BELADEB1DB6;0
M 10050007;D4;**100**;false;BELADEB1DB7;0  --  10050007;D4;000;false;BELADEB1DB7;0
M 10050008;**09;100**;false;BELADEB1DB8;0  --  10050008;E2;000;false;BELADEB1DB8;0
M 50021100;60;000;false;FFBKDEFF**XXX**;0  --  50021100;60;000;false;FFBKDEFFKRN;0
**A“ (Addition) --  50234500;09;000;false;KTAGDEFFXXX;0**
M 50863906;32;000;**false**;GENODE51ORM;0  --  50863906;32;000;true;GENODE51ORM;0
M 51091711;06;000;false;**BFOMD**E51XXX;0  --  51091711;06;000;false;VRBUDE51XXX;0
M 51210600;**00**;000;false;BNPADEFFXXX;0 -- 51210600;09;000;false;BNPADEFFXXX;0
**A“ (Addition) -- 51210801;09;000;false;SOGEDEFF1XX;0**
D 56062577;38;000;**true**;GENODED1VRK;0  --  56062577;38;000;false;GENODED1VRK;0
M 60069343;10;000;**false**;GENODES1RRI;0  --  60069343;10;000;true;GENODES1RRI;0
M 60069420;10;000;**false**;GENODES1MBI;0  --  60069420;10;000;true;GENODES1MBI;0
**A“ (Addition)  -- 0090133;10;000;false;VOBADESSXXX;0**
M 70120600;30;000;false;**RVSADEMX**XXX;0  --  70120600;30;000;false;AGBMDEMMXXX;0
D 76060561;88;100;**true**;GENODEF1N05;0  --  76060561;88;100;false;GENODEF1N05;0

why those differences are there? Am i missing something?
(left side is taken from blz file attached to the project)

**Comment by nittka** [comment]
The simplified blz file shipped with avacodo is from June, so it is not the latest one. By the way, you should not need to create this particular format. The reader can process the original file directly

https://github.com/infiniteam/avacodo/blob/master/avacodo-core/src/main/java/org/avacodo/filebased/SimpleBankConfigReader.xtend#L123

Does that help?

**Comment by quickquestion** [comment]
Thank you for your answer. I saw this method before and using big file is returning correct bic for 70120600 i.e. AGBMDEMMXXX, however i like the idea of simplified blz file (which is much smaller than the original one which has 3MB). To compare i used BLZ2_20150608.txt which i believe is the one which was used by you? Can you publish the file you used to generate simplified file (at least those few records i pasted here as those are the only one which are different, so i can ensure myself i am not doing any mistakes)?

**Comment by nittka** [comment]
I assume, you work from avacodo source code anyway. What you can do is just modify the SimpleBankConfigReader enabling lines 53, 57ff. The simplified version will then be created for you when processing the regular file.

Possibly your "error" (if it's on your side) is related to processing primary/non-primary bank codes (same bank code appearing in multiple lines)

**Comment by quickquestion** [comment]
Thank you for your time i will debug writeSimplifiedBlz (how could i mis this!)
